FORMAT: 1A
HOST: https://sandbox.karolina.io/agitator

# Agitator

An API for crowdfunding and crowdsourcing.

**Error handling:** All responses with code 200 should be considered successful but 5xx or 4xx not.

**Response status:** Responses should include the key *status* in the JSON which should be *success* for 200 responses,
but may include *error* or some other key depending on the context.

Error responses should include the field *message* which should be a human readable error message.

# Group Campaigns

## Campaigns [/campaigns/]

Campaigns are crowdfunding projects.

## Single campaign [/campaigns/{campaign_id}/{language}]

+ Parameters
    + campaign_id (string) - ID of the campaign
    + language (string) - The preferred language to return, e.g. en, is, fi

### Get campaign [GET]

+ Request (application/json)

    + Headers

            Authorization: Bearer <JWToken>

+ Response 200 (application/json)
    + Attributes (Campaign Response)

# Data Structures

## JWToken (string)

lkjsdsdjsdaf.lkjasdlfksdfj.laksjdflkjsadklj

## Acl (array)
A list of access control list levels.
## Sample
+ view
+ edit
+ admin

## Reward (object)
+ reward_id: 123 (string)
+ stock_reserved: 0 (number)
+ vat_percentage (string, nullable)
+ stock: 0 (number, nullable)
+ amount: 1 (number)
+ title: Low reward (string)
+ description: This is a low reward (string)
+ image (string, nullable)

## Rewards (array)
+ (Reward)

## Campaign (object)
+ rewards (Rewards)

## Campaign Response (object)
+ campaign (Campaign)
+ acl (Acl)